
apiVersion: v1
kind: Service
metadata:
  name: laravel
  labels:
    app: laravel
spec:
  type: NodePort
  ports:
  - port: 9000
    name: php-9000
  selector:
    app: laravel
---


apiVersion: v1
kind: Service
metadata:
  name: nginx-app
  labels:
    app: nginx-app
spec:
  type: NodePort
  ports:
  - nodePort: 32223
    port: 80
  selector:
    app: nginx-app

